export enum EventName {
    COURSE_CLICKED = "COURSE_CLICKED",
    USER_REGISTER = "USER_REGISTER",
    TEACHER_REGISTER = "TEACHER_REGISTER",
    COURSE_PUBLISHED = "COURSE_PUBLISHED",
    COURSE_CREATED = "COURSE_CREATED"
}
